# Generated by Django 5.2.8 on 2025-12-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetumart_app', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercaremessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customercaremessage',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20, null=True),
        ),
    ]
