# Generated by Django 5.2.8 on 2025-12-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetumart_app', '0005_chatmessage_order_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercaremessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
