# Generated by Django 4.2.27 on 2026-02-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetumart_app', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
