# Generated by Django 4.2.28 on 2026-02-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zetumart_app', '0008_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa_stk', 'M-Pesa STK Push'), ('mpesa_paybill', 'M-Pesa Paybill'), ('mpesa_till', 'M-Pesa Till'), ('mpesa_pochi', 'M-Pesa Pochi'), ('cod', 'Pay on Delivery'), ('polepole', 'Lipa Mdogo Mdogo'), ('card', 'Card Payment'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stk_push', 'M-Pesa STK Push'), ('paybill', 'M-Pesa Paybill/Till'), ('pochi', 'M-Pesa Pochi'), ('transaction_status', 'Transaction Status Query'), ('reversal', 'Transaction Reversal')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='zetumart_app.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
